server:
  port: 8080

spring:
  application:
    name: orchestrator

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.clinic.orch: INFO
    org.springframework.web: INFO
