apiVersion: v1
kind: Service
metadata:
  name: dm-service
  namespace: chatbot
  labels:
    app: dm
    component: dm
spec:
  selector:
    app: dm
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
