apiVersion: apps/v1
kind: Deployment
metadata:
  name: mam
  namespace: chatbot
  labels:
    app: mam
    component: mam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mam
  template:
    metadata:
      labels:
        app: mam
        component: mam
    spec:
      containers:
      - name: mam
        image: chatbot-mam:latest
        ports:
        - containerPort: 8002
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
