apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: chatbot
  labels:
    app: orchestrator
    component: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
